swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    post:
      tags:
        - User Module
      summary: User Account List API
      description: API for retrieving a list of user accounts.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: "string"
          required: true
        - in: body
          name: body
          description: UserID
          required: true
          schema:
            $ref: "#/definitions/Accounts"
      produces:
        - application/json
      responses:
        "200":
          description: Accounts retrieved successully
          schema:
            $ref: "#/definitions/AccountsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts/transactions:
    post:
      tags:
        - User Module
      summary: Account Transactions List API
      description: API for retrieving a list of transactions from an ID account.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: "string"
          required: true
        - in: body
          name: body
          description: User ID and Account ID
          required: true
          schema:
            $ref: "#/definitions/Transactions"
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Account Transactions edit API
      description: API for editing transactions details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: "string"
          required: true
        - in: body
          name: body
          description: Update transaction details
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transactions details updated successully
          schema:
            $ref: "#/definitions/EditTransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Accounts:
    type: object
    properties:
      userId:
        type: string

  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          userId:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          accounts:
            type: array
            items:
              type: object
              properties:
                accountId:
                  type: string
                accountName:
                  type: string
                accountBalance:
                  type: number

  Transactions:
    type: object
    properties:
      userId:
        type: string
      accountId:
        type: string

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          userId:
            type: string
          accountId:
            type: string
          transactions:
            type: array
            items:
              type: object
              properties:
                transactionId:
                  type: string
                date:
                  type: string
                amount:
                  type: string
                balance:
                  type: string
                description:
                  type: string
                type:
                  type: string
                category:
                  type: string
                notes:
                  type: string

  EditTransaction:
    type: object
    properties:
      transactionId:
        type: string
      type:
        type: string
      category:
        type: string
      notes:
        type: string

  EditTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactionId:
            type: string
          date:
            type: string
          amount:
            type: string
          balance:
            type: string
          description:
            type: string
          type:
            type: string
          category:
            type: string
          notes:
            type: string
